### ISSUE TITLE
`method` property cannot be set with external + label FFI

### ISSUE THREAD

**Issue by mransan** [BuckleTypes/bs-fetch#2]
[here](https://github.com/BuckleTypes/bs-fetch/blob/master/src/bs_fetch.ml#L276) is the problem. Since `method` is an OCaml keyword, it cannot be used as a label, when using `method_` as a label it creates a property `method_` which is not the desired outcome. 

@bobzhang Would there be a way to do [@bs.as "method"] on a label argument ?

A temporary solution could be to simply expose a `val setMethod : t -> requestMethod -> unit` function in `RequestInit` and remove the `~method_` labeled argument.

**Comment by glennsl** [comment]
Ah, this is because bs changed its name mangling not too long ago. Renaming it to ` _method`  should work. See https://bloomberg.github.io/bucklescript/Manual.html#_object_label_translation_convention. Could you verify this?

**Comment by mransan** [comment]
@glennsl it works! Thanks. I missed that part in the manual

**Comment by mransan** [comment]
@glennsl I am sending a new PR
