### ISSUE TITLE
fetchWithInit and credentials=Include not working or missing Docs

### ISSUE THREAD

**Issue by kivi** [BuckleTypes/bs-fetch#24]
I would like Fetch to send always the credentials, so cookies would be sent across domains not only on same-origin.

I am not sure anymore, if I had this working. The the compiled JavaScript is on a different Origin than the Request Origin. How could I possibly debug and check why it's failing?

```reason
Js.Promise.(
    Fetch.fetchWithInit(
      loginStatusUrl, 
      Fetch.RequestInit.make(~credentials=Include, ())
    )
    |> then_(Fetch.Response.json)
    |> catch(_err => resolve(None))
  );
```

**Comment by kivi** [comment]
It seems like it was an issue on my side. I tested on Windows 10 with FF and Chrome. With 3rd-Parties Cookies enabled and disabled.

But that example could be used for docs?

**Comment by glennsl** [comment]
`bs-fetch` is a very thin layer above the fetch API, and you're meant to be able to more or less directly translate fetch code to `bs-fetch`. Is there a gotcha here that you think should be pointed out in this example?

**Comment by kivi** [comment]
You are right. Better to place the explanation behind this layer.
