### ISSUE TITLE
use of readableStream type

### ISSUE THREAD

**Issue by joprice** [BuckleTypes/bs-fetch#32]
I see an abstract type `readableStream`, but nowhere is it an input parameter. Is there an example of using a streaming response body with fetch, or is it not implemented here yet?

**Comment by glennsl** [comment]
Sorry for the late response. That hasn't been implemented yet. At least as far as I'm aware. It's also kind of outside the scope of this project (hence the `external` comment). I'm also not entirely sure how to coordinate shared types across projects. Some DOM types have been added directly to `bs-platform` to facilitate interop, but that creates quite a bit of overhead for adding anything new. So for the moment it's just here as an abstract type. If you find a separate set of bindings for it that uses an incompatible type, you can always work around it by using an unsafe cast.

**Comment by dchambers** [comment]
This looks like it should support the `readableStream` opaque type from `bs-fetch`: https://reasonml-community.github.io/bs-webapi-incubator/api/Webapi/ReadableStream/
